/*
 * PSR Guam — site search.
 * Reads /assets/data/products.json (generated by scripts/build_catalog.py)
 * and gives every page a fuzzy, type-ahead product search box.
 * Needs a real HTTP server (Netlify, or `npx serve .` locally) — the
 * absolute "/assets/..." path won't resolve if you open a file directly
 * with file://.
 */
(function () {
  var input = document.getElementById("psrSearchInput");
  var resultsBox = document.getElementById("psrSearchResults");
  if (!input || !resultsBox) return;

  var fuse = null;
  var activeIndex = -1;

  fetch("/assets/data/products.json")
    .then(function (res) { return res.json(); })
    .then(function (products) {
      fuse = new Fuse(products, {
        keys: [
          { name: "name", weight: 0.4 },
          { name: "brand", weight: 0.3 },
          { name: "keywords", weight: 0.2 },
          { name: "description", weight: 0.1 },
        ],
        threshold: 0.25,
        minMatchCharLength: 2,
        ignoreLocation: true,
      });
    })
    .catch(function (err) {
      console.error("PSR search: could not load product data", err);
    });

  function render(matches) {
    activeIndex = -1;
    if (!matches.length) {
      resultsBox.innerHTML =
        '<div class="psr-search-empty">No matching products. ' +
        '<a href="/contact.html">Ask us for a quote</a> — we carry more than what\'s listed.</div>';
      resultsBox.classList.add("is-active");
      return;
    }
    resultsBox.innerHTML = matches
      .slice(0, 8)
      .map(function (p) {
        var tag = p.type === "subcategory"
          ? '<span class="psr-search-brand">Browse category</span>'
          : (p.brand ? '<span class="psr-search-brand">' + escapeHtml(p.brand) + "</span>" : "");
        return (
          '<a class="psr-search-result" href="' + p.url + '">' +
          '<span class="psr-search-name">' + escapeHtml(p.name) + "</span>" +
          tag +
          '<span class="psr-search-cat">' + escapeHtml(p.categoryName) + "</span>" +
          "</a>"
        );
      })
      .join("");
    resultsBox.classList.add("is-active");
  }

  function escapeHtml(str) {
    var div = document.createElement("div");
    div.textContent = str || "";
    return div.innerHTML;
  }

  function search() {
    var q = input.value.trim();
    if (!fuse || q.length < 2) {
      resultsBox.classList.remove("is-active");
      resultsBox.innerHTML = "";
      return;
    }
    // Fuse scores 0 = perfect match, 1 = no match - drop the loose tail
    // so a narrow query like "SKF" doesn't surface unrelated products.
    var matches = fuse
      .search(q)
      .filter(function (r) { return r.score === undefined || r.score <= 0.3; })
      .map(function (r) { return r.item; });
    render(matches);
  }

  var debounceTimer;
  input.addEventListener("input", function () {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(search, 120);
  });

  input.addEventListener("keydown", function (e) {
    var items = resultsBox.querySelectorAll(".psr-search-result");
    if (!items.length) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      activeIndex = Math.min(activeIndex + 1, items.length - 1);
      updateActive(items);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      activeIndex = Math.max(activeIndex - 1, 0);
      updateActive(items);
    } else if (e.key === "Enter") {
      if (activeIndex >= 0 && items[activeIndex]) {
        e.preventDefault();
        window.location.href = items[activeIndex].getAttribute("href");
      } else if (items[0]) {
        e.preventDefault();
        window.location.href = items[0].getAttribute("href");
      }
    } else if (e.key === "Escape") {
      resultsBox.classList.remove("is-active");
      input.blur();
    }
  });

  function updateActive(items) {
    items.forEach(function (el, i) {
      el.classList.toggle("is-active", i === activeIndex);
    });
  }

  document.addEventListener("click", function (e) {
    if (!e.target.closest("#psrSearch")) {
      resultsBox.classList.remove("is-active");
    }
  });
})();
